### ISSUE TITLE
Requires at least two (2) open tabs.

### ISSUE THREAD

**Issue by lawlist** [wulftone/sublime-text-quick-file-move#5]
Would it be possible to please implement a fix for a situation where only one (1) tab is open (i.e., the one being moved / renamed)?  The plugin works fine when there are at least two (2) open tabs.  When there is only one (1) open tab, the renamed file disappears and there are no longer any open tabs.

I'm using Sublime Text 2, latest stable release, on OSX operating system (Mountain Lion).

I like this version of the plugin because it displays the entire path, which is very useful in moving / renaming.

Thanks.

**Comment by wulftone** [comment]
I don't get that issue on linux, so I'm not sure I can help you.  It might be a sublime-text issue, and not due to this plugin.  Did you try any other renaming plugins?

**Comment by lawlist** [comment]
I found just one other plugin that looks similar to yours, except that the full path is not displayed.  It also has the same issue of closing the tab if it was the only one open -- the end result is no open tabs.

https://github.com/ariofrio/sublime-text-2-quick-file-renamer/blob/master/QuickRename.py

**Comment by lawlist** [comment]
You had a good idea.  Side bar enhancements works without having the side bar open.

https://github.com/titoBouzout/SideBarEnhancements

So, it is okay to close out this issue.  Thank you very much for the idea.
